//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   コマンド定義
        ///コマンド0
        ///コマンド1 パラメータ1
        ///コマンド2 パラメータ1,パラメータ2
        ///コマンド3 パラメータ1,パラメータ2,パラメータ3
        ///コマンド4 パラメータ1,パラメータ2,パラメータ3,パラメータ4
        ///
        ///ID:Script0
        ///Desc:スクリプトサンプル１
        ///コマンド0 
        ///コマンド1 にゃー
        ///コマンド2 にゃー,にゃにゃー
        ///コマンド3 にゃー,にゃにゃー,にゃにゃにゃー
        ///コマンド4 にゃー,にゃにゃー,にゃにゃにゃー,にゃーん
        ///
        ///ID:Script1
        ///Desc:スクリプトサンプル２
        ///コマンド4 にゃーお,にゃにゃーお,にゃにゃにゃーお,にゃおーん
        ///コマンド3 にゃーお,にゃにゃーお,にゃにゃにゃーお
        ///コマンド2 にゃーお,にゃにゃーお
        ///コマンド1 にゃーお
        ///コマンド0 
        ///
        ///ID:Script2
        ///Desc:スクリプトサンプル２
        ///コマンド0 
        ///コマンド1 みゃー
        ///コマンド2 みゃー,みゃみゃー
        ///コマンド3 みゃー,みゃみゃー,みゃみゃみゃー
        ///コマンド4 みゃー,みゃみゃー,みゃみゃみゃー,みゃおーん
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScriptFile {
            get {
                return ResourceManager.GetString("ScriptFile", resourceCulture);
            }
        }
    }
}
